[[redirects]]
  from = "/create_preference"
  to = "https://mascotasplus.netlify.app/create_preference"
  status = 200
  force = true

[[headers]]
  for = "/create_preference"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Credentials = true
